# Generated by Django 2.1.5 on 2019-02-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='msg_content',
            field=models.TextField(default=''),
        ),
    ]
