# Generated by Django 2.1.5 on 2019-02-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem_post', '0003_auto_20190228_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemtopic',
            name='problem_photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
