# Generated by Django 2.1.5 on 2019-02-28 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problem_post', '0004_auto_20190228_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemtopic',
            name='performer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performer', to=settings.AUTH_USER_MODEL),
        ),
    ]
