# Generated by Django 2.1.5 on 2019-02-24 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0001_initial'),
        ('problem_post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('photo', models.ImageField(upload_to='')),
                ('date_reg', models.DateTimeField(auto_now_add=True)),
                ('total_money_spend', models.IntegerField()),
                ('messages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.Message')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('problems_was', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem_post.ProblemTopic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MasterProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('photo', models.ImageField(upload_to='')),
                ('date_reg', models.DateTimeField(auto_now_add=True)),
                ('speciality', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('total_money_earn', models.IntegerField()),
                ('messages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.Message')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('problems_solved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problem_post.ProblemTopic')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
