# Generated by Django 2.1.5 on 2019-02-27 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='messages',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='messages',
            field=models.ManyToManyField(to='message.Message'),
        ),
        migrations.RemoveField(
            model_name='masterprofile',
            name='messages',
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='messages',
            field=models.ManyToManyField(to='message.Message'),
        ),
    ]
