# Generated by Django 2.1.5 on 2019-02-28 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190227_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='problems_was',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='problem_post.ProblemTopic'),
        ),
        migrations.AlterField(
            model_name='masterprofile',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
