# Generated by Django 2.1.5 on 2019-02-28 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190228_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='problems_was',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='problem_post.ProblemTopic'),
        ),
    ]
