# Generated by Django 2.1.5 on 2019-02-28 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190228_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterprofile',
            name='problems_solved',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='problem_post.ProblemTopic'),
        ),
    ]
