# Generated by Django 2.1.5 on 2019-02-28 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message_msg_content'),
        ('core', '0006_auto_20190228_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='messages',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='messages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='message.Message'),
        ),
        migrations.RemoveField(
            model_name='masterprofile',
            name='messages',
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='messages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='message.Message'),
        ),
    ]
