# Generated by Django 2.1.5 on 2019-03-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_message_msg_content'),
        ('core', '0007_auto_20190228_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='messages',
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='messages',
            field=models.ManyToManyField(blank=True, null=True, to='message.Message'),
        ),
        migrations.RemoveField(
            model_name='masterprofile',
            name='messages',
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='messages',
            field=models.ManyToManyField(blank=True, null=True, to='message.Message'),
        ),
    ]
